version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: progtalk-backend
    restart: always
    environment:
      MONGO_URI: mongodb://mongo:27017/progtalk
      FRONTEND_URL: https://localhost:5173
      PORT: 3002
    depends_on:
      - mongo
    networks:
      - progtalk-network
    volumes:
      - ./backend:/app
    expose:
      - "3002"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: progtalk-frontend
    restart: always
    environment:
      VITE_API_URL: https://localhost/api
      VITE_SOCKET_URL: https://localhost
    depends_on:
      - backend
    networks:
      - progtalk-network
    volumes:
      - ./frontend:/app
    expose:
      - "5173"

  nginx:
    image: nginx:alpine
    container_name: progtalk-nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend
    networks:
      - progtalk-network

  mongo:
    image: mongo
    container_name: progtalk-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: progtalk
    volumes:
      - progtalk-mongo-data:/data/db
    expose:
      - "27017"
    networks:
      - progtalk-network

networks:
  progtalk-network:
    driver: bridge

volumes:
  progtalk-mongo-data:
